name: 'Test Custom Action'
description: 'For Testing Purpose - description here'
author: 'Balmon'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  token: # change this
    required: true
    description: 'github token'
runs:
  using: 'node12'
  main: 'dist/index.js'
